/**
 * Copyright 2012 Subho Ghosh (subho.ghosh at outlook dot com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * @filename EnumJoinType.java
 * @created Sep 29, 2012
 * @author subhagho
 *
 */
package com.sqewd.open.dal.core.persistence.query;

/**
 * Enumerates the supported Join types.
 * 
 * @author subhagho
 * 
 */
public enum EnumJoinType {
	/**
	 * Internal Join, generated by reference keys.
	 */
	Internal,
	/**
	 * Native Join, uses the same persister, but join conditioned is specified.
	 */
	Native,
	/**
	 * External Join, uses a different persister and join condition is
	 * specified.
	 */
	External,
	/**
	 * Native entity, no joins required.
	 */
	None;
}
